{% set name = "boxing" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/boxing-{{ version }}.tar.gz
  sha256: b9141bd02d0fb5ebda881e727e16ce7c89034773282b29b8ce938a8117e79d1b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - boxing
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/acifani/boxing
  summary: Draw boxes like never before!
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
